name: Dependabot Auto Merge

on:
  pull_request:
    types:
      - labeled

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Auto-merge Dependabot PRs
        uses: pascalgn/automerge-action@v0.14.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          mergeMethod: rebase
          commitMessage: "chore(deps): auto-merge dependabot updates"
          mergeFilter: "label=automerge"
